"""Professional PDF clinical reports for DiagnoX AI Pro."""
from datetime import datetime
from fpdf import FPDF


def _safe(text):
    if not text:
        return ""
    return (
        str(text)
        .replace("\u2014", "-")
        .replace("\u2013", "-")
        .replace("\u2018", "'")
        .replace("\u2019", "'")
        .replace("\u201c", '"')
        .replace("\u201d", '"')
        .encode("latin-1", "replace")
        .decode("latin-1")
    )


class DiagnoXReportPDF(FPDF):
    def header(self):
        self.set_fill_color(29, 125, 252)
        self.rect(0, 0, 210, 28, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 18)
        self.set_y(8)
        self.cell(0, 10, "DiagnoX AI Pro - Clinical Report", 0, 1, "C")
        self.ln(14)

    def footer(self):
        self.set_y(-18)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(
            0,
            8,
            _safe(
                "Educational triage only. Not a substitute for professional medical diagnosis. "
                f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}"
            ),
            0,
            0,
            "C",
        )

    def section_title(self, title):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(29, 125, 252)
        self.cell(0, 9, _safe(title), 0, 1, "L")
        self.set_draw_color(29, 125, 252)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)
        self.set_text_color(30, 30, 30)

    def body_text(self, text):
        self.set_font("Helvetica", "", 11)
        self.multi_cell(0, 6, _safe(text))
        self.ln(3)

    def info_box(self, lines):
        self.set_fill_color(248, 250, 252)
        self.set_draw_color(226, 232, 240)
        y0 = self.get_y()
        self.rect(10, y0, 190, 8 + len(lines) * 7, "DF")
        self.set_xy(14, y0 + 4)
        self.set_font("Helvetica", "", 10)
        for line in lines:
            self.cell(0, 6, _safe(line), 0, 1, "L")
            self.set_x(14)
        self.ln(6)


def build_clinical_advice(suggestion, risk, severity):
    """Split suggestion into home remedy and doctor advice sections."""
    base = (suggestion or "Rest, stay hydrated, and monitor symptoms.").strip().strip('"')
    home = base
    doctor = (
        "Clinical recommendations based on AI triage:\n\n"
        f"- Primary assessment: {base}\n\n"
        "- Schedule an in-person or telehealth consultation with a licensed physician "
        "for examination, vitals, and confirmatory tests.\n"
        "- Seek urgent/emergency care immediately if you experience chest pain, "
        "severe breathlessness, confusion, persistent high fever, or rapid worsening.\n"
        f"- Documented severity: {severity.title()}. Triage risk level: {risk}.\n"
        "- Do not start, stop, or change prescription medication without medical supervision."
    )
    return home, doctor


def generate_analysis_pdf(entry, clinician_name="Clinician", clinician_role="Clinician"):
    """Build PDF bytes from a history entry dict."""
    pdf = DiagnoXReportPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    home = entry.get("home_remedy") or entry.get("suggestion", "")
    doctor = entry.get("doctor_advice") or entry.get("suggestion", "")
    symptoms = entry.get("symptoms") or []
    symptom_text = ", ".join(s.replace("_", " ").title() for s in symptoms) if symptoms else "Not recorded"

    pdf.info_box([
        f"Clinician: Dr. {clinician_name} ({clinician_role})",
        f"Patient: {entry.get('patient', 'N/A')}",
        f"Date: {entry.get('date', datetime.now().strftime('%b %d, %Y'))}",
        f"Symptoms reported: {entry.get('symptoms_count', 0)}",
        f"Severity: {(entry.get('severity') or 'moderate').title()}",
        f"Risk level: {entry.get('risk', 'N/A')}",
    ])

    pdf.section_title("Reported Symptoms")
    pdf.body_text(symptom_text)

    pdf.section_title("AI Diagnosis")
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, _safe(entry.get("prediction", "Unknown")), 0, 1, "L")
    pdf.ln(2)

    pdf.section_title("Home Remedies & Self-Care")
    pdf.body_text(
        "The following home-care measures may help while you arrange professional care. "
        "These are supportive steps only and do not replace medical treatment:\n\n"
        f"{home}"
    )

    pdf.section_title("Doctor's Medical Advice")
    pdf.body_text(doctor)

    pdf.section_title("Important Notice")
    pdf.body_text(
        "This report was generated by DiagnoX AI Pro for preliminary clinical triage. "
        "A qualified healthcare provider must confirm any diagnosis and prescribe treatment."
    )

    raw = pdf.output(dest="S")
    if isinstance(raw, (bytes, bytearray)):
        return bytes(raw)
    return raw.encode("latin-1")
